title:              Steve's Blog
email:              stemahon@gmail.com
description:        Writings about projects and interests
author:             Stephen Mahon
baseurl:            ""
url:                "https://stephen-mahon.github.io"

# Social Profiles
twitter_username:   stiofanomathuna
github_username:    stephen-mahon
facebook_username:  
instagram_username:  
linkedin_username:  stephentmahon

# Add your google-analytics ID here to activate google analytics
google_analytics:   #UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

sass:
  sass_dir: _sass
  style: compressed